### ISSUE TITLE
Ironsights not changing at all

### ISSUE THREAD

**Issue by ExidiusCrimson** [vingard/longsword#3]
I am using different view models, even the normal hl2 ones. Whatever I do the iron sights do not move by an inch. Here's an example.
![rp_ineu_valley2_v1a0000](https://user-images.githubusercontent.com/66439426/103030417-0bab1000-455c-11eb-8c66-dab8e9ffc316.jpg)

**Comment by vingard** [comment]
Ironsights are defined in the weapons script. These two values must be changed to move the position.
`SWEP.IronsightsPos = Vector(-4.7, 0, 0.56)
SWEP.IronsightsAng = Angle(0.2, -0.201, 0)`

**Comment by ExidiusCrimson** [comment]
> Ironsights are defined in the weapons script. These two values must be changed to move the position.
> 
> ```
> SWEP.IronsightsPos = Vector(-4.7, 0, 0.56) 
> SWEP.IronsightsAng = Angle(0.2, -0.201, 0)
> ```

That is what I'm doing, but whatever the value gets changed to the position will be the same.

**Comment by vingard** [comment]
> 
> 
> > Ironsights are defined in the weapons script. These two values must be changed to move the position.
> > ```
> > SWEP.IronsightsPos = Vector(-4.7, 0, 0.56) 
> > SWEP.IronsightsAng = Angle(0.2, -0.201, 0)
> > ```
> 
> That is what I'm doing, but whatever the value gets changed to the position will be the same.

Have you tried reloading your game, and try changing the values by an extreme amount just to check that they actually are changing.

**Comment by ExidiusCrimson** [comment]
> > > Ironsights are defined in the weapons script. These two values must be changed to move the position.
> > > ```
> > > SWEP.IronsightsPos = Vector(-4.7, 0, 0.56) 
> > > SWEP.IronsightsAng = Angle(0.2, -0.201, 0)
> > > ```
> > 
> > 
> > That is what I'm doing, but whatever the value gets changed to the position will be the same.
> 
> Have you tried reloading your game, and try changing the values by an extreme amount just to check that they actually are changing.

Tried reloading and restarting, yet have to try putting amounts to maximum.

**Comment by ExidiusCrimson** [comment]
The ironsights never change no matter what i do. I have sent you a friend request on Discord, my tag is Exidius#3660
